CREATE TABLE JOB
(
  ID SERIAL NOT NULL
    PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  STAGE INTEGER NOT NULL,
  CUSTOMER_ID INTEGER NOT NULL REFERENCES CUSTOMER(ID),
  PRODUCT_ID INTEGER NOT NULL REFERENCES PRODUCT(ID)
);
