create table EMPLOYEE
(
  ID SERIAL NOT NULL
    primary key,
  FIRST_NAME VARCHAR(24) NOT NULL,
  LAST_NAME VARCHAR(24) not null,
  EMAIL VARCHAR(50) UNIQUE NOT NULL,
  PHONE VARCHAR (11) NOT NULL
);

